var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/negotiate/route.js")
R.c("server/chunks/node_modules_@vercel_oidc_dist_6505c815._.js")
R.c("server/chunks/node_modules_next_63a8c133._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_zod_7a81769b._.js")
R.c("server/chunks/node_modules_@ai-sdk_openai_dist_index_mjs_19cd50d6._.js")
R.c("server/chunks/node_modules_ai_dist_index_mjs_b0116780._.js")
R.c("server/chunks/node_modules_3cf9dd36._.js")
R.c("server/chunks/[root-of-the-server]__0aa20d1a._.js")
R.c("server/chunks/_next-internal_server_app_api_negotiate_route_actions_9906d50e.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/negotiate/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/negotiate/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
